services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    image: nginx
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - "443:443"
    restart: always
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_files:/var/www/html
    env_file:
      - .env
    restart: always
volumes:
  wordpress_files:
    driver: local
    driver_opts:
      device: "/home/fbosch/Data/wordpress_files"
      o: bind
      type: none
