services:
  mariadb:
    build: requirements/mariadb/
    volumes:
      - test_data:/var
volumes:
  test_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ferran
